name: Laravel CI

# Jalankan action saat ada push atau pull request ke branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        # Tunggu sampai MySQL siap sebelum menjalankan jobs
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Step untuk checkout kode repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step untuk mengatur versi PHP yang digunakan
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Versi PHP yang digunakan
          extensions: mbstring, pdo_mysql, bcmath
          ini-values: post_max_size=256M, max_execution_time=300

      # Step untuk cache dependencies Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # Step untuk menginstal dependencies Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step untuk menginstal NPM dependencies
      - name: Install NPM dependencies
        run: npm install && npm run dev

      # Step untuk membuat file .env
      - name: Setup .env file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Step untuk migrasi database
      - name: Run database migrations
        run: php artisan migrate --force
